-- HoopLoop Version 7 online database
-- Run this entire file in a NEW Supabase project's SQL Editor.
-- It creates accounts/profile support, daily scores, practice records,
-- friends, and realtime head-to-head race tables/functions.

create extension if not exists citext;
create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username citext not null unique,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint profiles_username_format check (username::text ~ '^[A-Za-z0-9_]{3,18}$')
);

create table if not exists public.daily_scores (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  puzzle_date date not null,
  puzzle_signature text not null,
  time_ms integer not null check (time_ms between 1500 and 600000),
  hints_used integer not null default 0 check (hints_used between 0 and 30),
  round_splits jsonb not null default '[]'::jsonb,
  submitted_at timestamptz not null default now(),
  unique (user_id, puzzle_date)
);

create table if not exists public.practice_sessions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  difficulty text not null check (difficulty in ('rookie','starter','allstar','mvp')),
  round_count integer not null check (round_count between 1 and 1000),
  correct_count integer not null check (correct_count between 0 and round_count),
  time_ms integer not null check (time_ms between 1 and 86400000),
  best_round_ms integer,
  hints_used integer not null default 0 check (hints_used >= 0),
  created_at timestamptz not null default now()
);

create table if not exists public.friendships (
  id uuid primary key default gen_random_uuid(),
  requester_id uuid not null references public.profiles(id) on delete cascade,
  addressee_id uuid not null references public.profiles(id) on delete cascade,
  status text not null default 'pending' check (status in ('pending','accepted','declined')),
  created_at timestamptz not null default now(),
  responded_at timestamptz,
  constraint friendships_not_self check (requester_id <> addressee_id)
);

create unique index if not exists friendships_unique_pair
  on public.friendships (least(requester_id, addressee_id), greatest(requester_id, addressee_id));

create table if not exists public.race_matches (
  id uuid primary key default gen_random_uuid(),
  host_id uuid not null references public.profiles(id) on delete cascade,
  opponent_id uuid references public.profiles(id) on delete set null,
  winner_id uuid references public.profiles(id) on delete set null,
  match_type text not null check (match_type in ('random','friend')),
  status text not null default 'waiting' check (status in ('waiting','invited','active','finished','cancelled')),
  rounds jsonb not null,
  starts_at timestamptz,
  created_at timestamptz not null default now(),
  finished_at timestamptz,
  constraint race_rounds_three check (jsonb_typeof(rounds) = 'array' and jsonb_array_length(rounds) = 3),
  constraint race_not_self check (opponent_id is null or host_id <> opponent_id)
);

create table if not exists public.race_progress (
  match_id uuid not null references public.race_matches(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  round_index integer not null default 0 check (round_index between 0 and 3),
  elapsed_ms integer check (elapsed_ms is null or elapsed_ms between 0 and 3600000),
  hints_used integer not null default 0 check (hints_used >= 0),
  finished_at timestamptz,
  updated_at timestamptz not null default now(),
  primary key (match_id, user_id)
);

create index if not exists daily_scores_date_time_idx on public.daily_scores (puzzle_date, time_ms, submitted_at);
create index if not exists daily_scores_user_idx on public.daily_scores (user_id, puzzle_date desc);
create index if not exists practice_sessions_user_idx on public.practice_sessions (user_id, created_at desc);
create index if not exists friendships_requester_idx on public.friendships (requester_id, status);
create index if not exists friendships_addressee_idx on public.friendships (addressee_id, status);
create index if not exists race_matches_waiting_idx on public.race_matches (match_type, status, created_at);
create index if not exists race_matches_opponent_idx on public.race_matches (opponent_id, status, created_at desc);
create index if not exists race_progress_match_idx on public.race_progress (match_id, updated_at);

create or replace function public.touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists profiles_touch_updated_at on public.profiles;
create trigger profiles_touch_updated_at
before update on public.profiles
for each row execute function public.touch_updated_at();

drop trigger if exists race_progress_touch_updated_at on public.race_progress;
create trigger race_progress_touch_updated_at
before update on public.race_progress
for each row execute function public.touch_updated_at();

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  requested_username text;
begin
  requested_username := coalesce(new.raw_user_meta_data ->> 'username', split_part(coalesce(new.email, ''), '@', 1));

  if requested_username !~ '^[A-Za-z0-9_]{3,18}$' then
    raise exception 'Username must contain 3-18 letters, numbers, or underscores.';
  end if;

  insert into public.profiles (id, username)
  values (new.id, requested_username);

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_user();

-- Row Level Security
alter table public.profiles enable row level security;
alter table public.daily_scores enable row level security;
alter table public.practice_sessions enable row level security;
alter table public.friendships enable row level security;
alter table public.race_matches enable row level security;
alter table public.race_progress enable row level security;

drop policy if exists "profiles are publicly readable" on public.profiles;
create policy "profiles are publicly readable"
on public.profiles for select
using (true);

drop policy if exists "users update own profile" on public.profiles;
create policy "users update own profile"
on public.profiles for update
to authenticated
using ((select auth.uid()) = id)
with check ((select auth.uid()) = id);

drop policy if exists "daily scores are publicly readable" on public.daily_scores;
create policy "daily scores are publicly readable"
on public.daily_scores for select
using (true);

drop policy if exists "users read own practice sessions" on public.practice_sessions;
create policy "users read own practice sessions"
on public.practice_sessions for select
to authenticated
using ((select auth.uid()) = user_id);

drop policy if exists "users insert own practice sessions" on public.practice_sessions;
create policy "users insert own practice sessions"
on public.practice_sessions for insert
to authenticated
with check ((select auth.uid()) = user_id);

drop policy if exists "friendship participants can read" on public.friendships;
create policy "friendship participants can read"
on public.friendships for select
to authenticated
using ((select auth.uid()) in (requester_id, addressee_id));

drop policy if exists "race participants can read matches" on public.race_matches;
create policy "race participants can read matches"
on public.race_matches for select
to authenticated
using ((select auth.uid()) in (host_id, opponent_id));

drop policy if exists "race participants can read progress" on public.race_progress;
create policy "race participants can read progress"
on public.race_progress for select
to authenticated
using (
  exists (
    select 1 from public.race_matches m
    where m.id = race_progress.match_id
      and (select auth.uid()) in (m.host_id, m.opponent_id)
  )
);

-- Daily scoring RPC: one official score per user/date.
create or replace function public.submit_daily_score(
  p_puzzle_date date,
  p_puzzle_signature text,
  p_time_ms integer,
  p_hints_used integer,
  p_round_splits jsonb
)
returns public.daily_scores
language plpgsql
security definer
set search_path = public
as $$
declare
  uid uuid := auth.uid();
  saved public.daily_scores;
begin
  if uid is null then raise exception 'Authentication required.'; end if;
  if p_puzzle_date is null or length(trim(coalesce(p_puzzle_signature, ''))) < 5 then
    raise exception 'Invalid puzzle.';
  end if;
  if p_time_ms < 1500 or p_time_ms > 600000 then raise exception 'Invalid completion time.'; end if;
  if p_hints_used < 0 or p_hints_used > 30 then raise exception 'Invalid hint count.'; end if;
  if jsonb_typeof(p_round_splits) <> 'array' or jsonb_array_length(p_round_splits) <> 3 then
    raise exception 'Three round splits are required.';
  end if;

  insert into public.daily_scores (user_id, puzzle_date, puzzle_signature, time_ms, hints_used, round_splits)
  values (uid, p_puzzle_date, upper(p_puzzle_signature), p_time_ms, p_hints_used, p_round_splits)
  on conflict (user_id, puzzle_date) do nothing
  returning * into saved;

  if saved.id is null then
    raise exception 'You already have an official score for this daily puzzle.';
  end if;
  return saved;
end;
$$;

create or replace function public.send_friend_request_by_username(p_username text)
returns public.friendships
language plpgsql
security definer
set search_path = public
as $$
declare
  uid uuid := auth.uid();
  target_id uuid;
  existing public.friendships;
  result public.friendships;
begin
  if uid is null then raise exception 'Authentication required.'; end if;
  select id into target_id from public.profiles where username = p_username::citext;
  if target_id is null then raise exception 'Username not found.'; end if;
  if target_id = uid then raise exception 'You cannot add yourself.'; end if;

  select * into existing from public.friendships
  where least(requester_id, addressee_id) = least(uid, target_id)
    and greatest(requester_id, addressee_id) = greatest(uid, target_id)
  limit 1;

  if existing.id is not null then
    if existing.status = 'accepted' then raise exception 'You are already friends.'; end if;
    if existing.status = 'pending' then raise exception 'A friend request is already pending.'; end if;
    update public.friendships
      set requester_id = uid, addressee_id = target_id, status = 'pending', created_at = now(), responded_at = null
      where id = existing.id returning * into result;
    return result;
  end if;

  insert into public.friendships (requester_id, addressee_id)
  values (uid, target_id) returning * into result;
  return result;
end;
$$;

create or replace function public.respond_friend_request(p_friendship_id uuid, p_accept boolean)
returns public.friendships
language plpgsql
security definer
set search_path = public
as $$
declare
  uid uuid := auth.uid();
  result public.friendships;
begin
  if uid is null then raise exception 'Authentication required.'; end if;
  update public.friendships
  set status = case when p_accept then 'accepted' else 'declined' end,
      responded_at = now()
  where id = p_friendship_id and addressee_id = uid and status = 'pending'
  returning * into result;
  if result.id is null then raise exception 'Friend request is no longer available.'; end if;
  return result;
end;
$$;

create or replace function public.remove_friend(p_friendship_id uuid)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  uid uuid := auth.uid();
  removed integer;
begin
  if uid is null then raise exception 'Authentication required.'; end if;
  delete from public.friendships
  where id = p_friendship_id and uid in (requester_id, addressee_id);
  get diagnostics removed = row_count;
  return removed > 0;
end;
$$;

create or replace function public.join_random_race(p_rounds jsonb)
returns public.race_matches
language plpgsql
security definer
set search_path = public
as $$
declare
  uid uuid := auth.uid();
  found_match public.race_matches;
begin
  if uid is null then raise exception 'Authentication required.'; end if;
  if jsonb_typeof(p_rounds) <> 'array' or jsonb_array_length(p_rounds) <> 3 then
    raise exception 'A race requires exactly three rounds.';
  end if;

  select * into found_match
  from public.race_matches
  where match_type = 'random'
    and status = 'waiting'
    and opponent_id is null
    and host_id <> uid
    and created_at > now() - interval '5 minutes'
  order by created_at
  for update skip locked
  limit 1;

  if found_match.id is not null then
    update public.race_matches
      set opponent_id = uid, status = 'active', starts_at = now() + interval '5 seconds'
      where id = found_match.id
      returning * into found_match;
    insert into public.race_progress (match_id, user_id)
      values (found_match.id, found_match.host_id), (found_match.id, uid)
      on conflict do nothing;
    return found_match;
  end if;

  insert into public.race_matches (host_id, match_type, status, rounds)
  values (uid, 'random', 'waiting', p_rounds)
  returning * into found_match;
  insert into public.race_progress (match_id, user_id) values (found_match.id, uid);
  return found_match;
end;
$$;

create or replace function public.create_friend_race(p_friend_username text, p_rounds jsonb)
returns public.race_matches
language plpgsql
security definer
set search_path = public
as $$
declare
  uid uuid := auth.uid();
  friend_id uuid;
  result public.race_matches;
begin
  if uid is null then raise exception 'Authentication required.'; end if;
  if jsonb_typeof(p_rounds) <> 'array' or jsonb_array_length(p_rounds) <> 3 then
    raise exception 'A race requires exactly three rounds.';
  end if;
  select id into friend_id from public.profiles where username = p_friend_username::citext;
  if friend_id is null then raise exception 'Friend not found.'; end if;
  if not exists (
    select 1 from public.friendships f
    where f.status = 'accepted'
      and ((f.requester_id = uid and f.addressee_id = friend_id) or (f.requester_id = friend_id and f.addressee_id = uid))
  ) then raise exception 'You can only challenge accepted friends.'; end if;

  insert into public.race_matches (host_id, opponent_id, match_type, status, rounds)
  values (uid, friend_id, 'friend', 'invited', p_rounds)
  returning * into result;
  insert into public.race_progress (match_id, user_id)
    values (result.id, uid), (result.id, friend_id)
    on conflict do nothing;
  return result;
end;
$$;

create or replace function public.accept_race(p_match_id uuid)
returns public.race_matches
language plpgsql
security definer
set search_path = public
as $$
declare
  uid uuid := auth.uid();
  result public.race_matches;
begin
  if uid is null then raise exception 'Authentication required.'; end if;
  update public.race_matches
    set status = 'active', starts_at = now() + interval '5 seconds'
    where id = p_match_id and opponent_id = uid and status = 'invited'
    returning * into result;
  if result.id is null then raise exception 'Race invitation is no longer available.'; end if;
  return result;
end;
$$;

create or replace function public.decline_or_leave_race(p_match_id uuid)
returns public.race_matches
language plpgsql
security definer
set search_path = public
as $$
declare
  uid uuid := auth.uid();
  current_match public.race_matches;
  other_id uuid;
begin
  if uid is null then raise exception 'Authentication required.'; end if;
  select * into current_match from public.race_matches
    where id = p_match_id and uid in (host_id, opponent_id)
    for update;
  if current_match.id is null then raise exception 'Race not found.'; end if;

  if current_match.status = 'active' then
    other_id := case when current_match.host_id = uid then current_match.opponent_id else current_match.host_id end;
    update public.race_matches
      set status = 'finished', winner_id = other_id, finished_at = now()
      where id = p_match_id
      returning * into current_match;
  elsif current_match.status in ('waiting','invited') then
    update public.race_matches set status = 'cancelled', finished_at = now()
      where id = p_match_id returning * into current_match;
  end if;
  return current_match;
end;
$$;

create or replace function public.submit_race_progress(
  p_match_id uuid,
  p_round_index integer,
  p_elapsed_ms integer,
  p_hints_used integer,
  p_finished boolean default false
)
returns public.race_matches
language plpgsql
security definer
set search_path = public
as $$
declare
  uid uuid := auth.uid();
  current_match public.race_matches;
begin
  if uid is null then raise exception 'Authentication required.'; end if;
  if p_round_index < 0 or p_round_index > 3 then raise exception 'Invalid race progress.'; end if;
  if p_elapsed_ms < 0 or p_elapsed_ms > 3600000 then raise exception 'Invalid race time.'; end if;

  select * into current_match from public.race_matches
  where id = p_match_id and uid in (host_id, opponent_id)
  for update;
  if current_match.id is null then raise exception 'Race not found.'; end if;
  if current_match.status <> 'active' then return current_match; end if;
  if current_match.starts_at is null or current_match.starts_at > now() + interval '1 second' then
    raise exception 'Race has not started.';
  end if;

  insert into public.race_progress (match_id, user_id, round_index, elapsed_ms, hints_used, finished_at)
  values (p_match_id, uid, p_round_index, p_elapsed_ms, p_hints_used, case when p_finished then now() else null end)
  on conflict (match_id, user_id) do update
    set round_index = greatest(race_progress.round_index, excluded.round_index),
        elapsed_ms = greatest(coalesce(race_progress.elapsed_ms, 0), excluded.elapsed_ms),
        hints_used = greatest(race_progress.hints_used, excluded.hints_used),
        finished_at = coalesce(race_progress.finished_at, excluded.finished_at);

  if p_finished and p_round_index = 3 then
    update public.race_matches
      set winner_id = uid, status = 'finished', finished_at = now()
      where id = p_match_id and winner_id is null
      returning * into current_match;
    if current_match.id is null then
      select * into current_match from public.race_matches where id = p_match_id;
    end if;
  else
    select * into current_match from public.race_matches where id = p_match_id;
  end if;
  return current_match;
end;
$$;

-- Function permissions. Browser clients receive only the anon/public key;
-- RLS and these authenticated-only RPC grants protect writes.
revoke all on function public.submit_daily_score(date,text,integer,integer,jsonb) from public, anon;
revoke all on function public.send_friend_request_by_username(text) from public, anon;
revoke all on function public.respond_friend_request(uuid,boolean) from public, anon;
revoke all on function public.remove_friend(uuid) from public, anon;
revoke all on function public.join_random_race(jsonb) from public, anon;
revoke all on function public.create_friend_race(text,jsonb) from public, anon;
revoke all on function public.accept_race(uuid) from public, anon;
revoke all on function public.decline_or_leave_race(uuid) from public, anon;
revoke all on function public.submit_race_progress(uuid,integer,integer,integer,boolean) from public, anon;

grant execute on function public.submit_daily_score(date,text,integer,integer,jsonb) to authenticated;
grant execute on function public.send_friend_request_by_username(text) to authenticated;
grant execute on function public.respond_friend_request(uuid,boolean) to authenticated;
grant execute on function public.remove_friend(uuid) to authenticated;
grant execute on function public.join_random_race(jsonb) to authenticated;
grant execute on function public.create_friend_race(text,jsonb) to authenticated;
grant execute on function public.accept_race(uuid) to authenticated;
grant execute on function public.decline_or_leave_race(uuid) to authenticated;
grant execute on function public.submit_race_progress(uuid,integer,integer,integer,boolean) to authenticated;

grant select on public.profiles, public.daily_scores to anon, authenticated;
grant select, insert on public.practice_sessions to authenticated;
grant select on public.friendships, public.race_matches, public.race_progress to authenticated;

-- Realtime updates for races, invitations, friends, and leaderboards.
alter table public.race_matches replica identity full;
alter table public.race_progress replica identity full;
alter table public.friendships replica identity full;
alter table public.daily_scores replica identity full;

do $$
begin
  if not exists (select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='race_matches') then
    alter publication supabase_realtime add table public.race_matches;
  end if;
  if not exists (select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='race_progress') then
    alter publication supabase_realtime add table public.race_progress;
  end if;
  if not exists (select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='friendships') then
    alter publication supabase_realtime add table public.friendships;
  end if;
  if not exists (select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='daily_scores') then
    alter publication supabase_realtime add table public.daily_scores;
  end if;
end $$;

-- Quick verification query. It should return six rows after setup.
select table_name
from information_schema.tables
where table_schema='public'
  and table_name in ('profiles','daily_scores','practice_sessions','friendships','race_matches','race_progress')
order by table_name;
