(() => {
'use strict';
const DATA=window.HOOPLOOP_STATS_RACE_DATA||{players:[],meta:{}};
const PLAYERS=DATA.players||[];
const MAX_SCORE=1700, RACE_MS=90000;
const $=id=>document.getElementById(id), qsa=s=>[...document.querySelectorAll(s)];
const cfg=window.HOOPLOOP_CONFIG||{};
const configured=Boolean(window.supabase)&&/^https:\/\/.+\.supabase\.co$/i.test(String(cfg.SUPABASE_URL||''))&&Boolean(cfg.SUPABASE_ANON_KEY)&&!String(cfg.SUPABASE_ANON_KEY).includes('PASTE_');
const db=configured?window.supabase.createClient(cfg.SUPABASE_URL,cfg.SUPABASE_ANON_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}}):null;
const FIELDS=[
 {id:'height',label:'Height',type:'height',get:p=>p.heightInches,display:v=>`${Math.floor(v/12)}'${v%12}\"`},
 {id:'weight',label:'Weight',type:'weight',get:p=>p.weight,display:v=>`${v} lb`},
 {id:'position',label:'Primary position',type:'text',get:p=>p.primaryPosition,aliases:p=>p.positionAliases,display:v=>v},
 {id:'college',label:'College / route',type:'text',get:p=>p.college,aliases:p=>p.collegeAliases,display:v=>v},
 {id:'hometown',label:'Hometown / birthplace',type:'text',get:p=>p.hometown,aliases:p=>p.hometownAliases,display:v=>v},
 {id:'jersey',label:'Jersey number',type:'jersey',get:p=>p.jerseyNumbers[0],alts:p=>p.jerseyNumbers,display:v=>`#${v}`},
 {id:'draftYear',label:'Draft year',type:'year',get:p=>p.draftYear,display:v=>String(v)},
 {id:'draftPick',label:'Draft pick',type:'pick',get:p=>p.draftPick,display:v=>`#${v}`},
 {id:'championships',label:'Championships',type:'award',get:p=>p.championships,display:v=>String(v)},
 {id:'mvps',label:'Regular-season MVPs',type:'award',get:p=>p.mvps,display:v=>String(v)},
 {id:'finalsMvps',label:'Finals MVPs',type:'award',get:p=>p.finalsMvps,display:v=>String(v)},
 {id:'allStars',label:'All-Star selections',type:'allstar',get:p=>p.allStars,display:v=>String(v)},
 {id:'games',label:'Games played',type:'games',get:p=>p.games,display:v=>Number(v).toLocaleString()},
 {id:'points',label:'Career points',type:'points',get:p=>p.points,display:v=>Number(v).toLocaleString()},
 {id:'ppg',label:'PPG',type:'average',get:p=>p.ppg,display:v=>Number(v).toFixed(1)},
 {id:'rpg',label:'RPG',type:'average',get:p=>p.rpg,display:v=>Number(v).toFixed(1)},
 {id:'apg',label:'APG',type:'average',get:p=>p.apg,display:v=>Number(v).toFixed(1)}
];
const state={mode:'daily',player:null,running:false,startAt:0,endAt:0,timer:null,answers:null,breakdown:null,score:0,timeMs:0,user:null,profile:null,dailyRow:null,cpuScore:null,match:null,channel:null,matchRole:null,lastPractice:null};
function escapeHtml(s){return String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
function norm(s){return String(s??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toUpperCase().replace(/[^A-Z0-9]+/g,' ').trim();}
function clamp(v,a,b){return Math.max(a,Math.min(b,v));}
function hash(str){let h=2166136261;for(let i=0;i<str.length;i++){h^=str.charCodeAt(i);h=Math.imul(h,16777619);}return h>>>0;}
function todayCentral(){const parts=new Intl.DateTimeFormat('en-US',{timeZone:'America/Chicago',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date());const o={};parts.forEach(p=>o[p.type]=p.value);return `${o.year}-${o.month}-${o.day}`;}
function dailyPlayer(date=todayCentral()){return PLAYERS[hash(`stats-race-v1:${date}`)%PLAYERS.length];}
function randomPlayer(excludeId=''){const pool=PLAYERS.filter(p=>p.id!==excludeId);return pool[Math.floor(Math.random()*pool.length)]||PLAYERS[0];}
function toast(title,msg='',kind='success'){const n=document.createElement('div');n.className=`toast ${kind}`;n.innerHTML=`<strong>${escapeHtml(title)}</strong>${msg?`<div>${escapeHtml(msg)}</div>`:''}`;$('toast-region').appendChild(n);setTimeout(()=>n.remove(),4200);}
function openModal(html){$('modal-content').innerHTML=html;$('modal-backdrop').classList.remove('hidden');}
function closeModal(){$('modal-backdrop').classList.add('hidden');$('modal-content').innerHTML='';}
function parseHeight(v){const s=String(v||'').trim();if(!s)return NaN;const nums=s.match(/\d+(?:\.\d+)?/g)||[];if(s.includes("'")||nums.length>=2){const ft=Number(nums[0]),inch=Number(nums[1]||0);return ft*12+inch;}const n=Number(nums[0]);if(!Number.isFinite(n))return NaN;if(n>=48&&n<=100)return n;if(n>=5&&n<8)return Math.round(n*12);return NaN;}
function numericValue(id){const v=$(id).value.trim();return v===''?NaN:Number(v);}
function textScore(raw,aliases){const guess=norm(raw);if(!guess)return 0;const vals=(aliases||[]).map(norm);if(vals.includes(guess))return 100;for(const a of vals){if(guess.length>=4&&(a.includes(guess)||guess.includes(a)))return 85;}return 0;}
function numericScore(type,guess,answer,alts=[]){if(!Number.isFinite(guess))return 0;const d=Math.min(...([answer,...alts].filter(Number.isFinite).map(a=>Math.abs(guess-a))));switch(type){case'height':return Math.round(clamp(100-d*25,0,100));case'weight':return Math.round(clamp(100-d*5,0,100));case'jersey':return Math.round(clamp(100-d*20,0,100));case'year':return Math.round(clamp(100-d*25,0,100));case'pick':return Math.round(clamp(100-d*10,0,100));case'award':return Math.round(clamp(100-d*30,0,100));case'allstar':return Math.round(clamp(100-d*12,0,100));case'games':return Math.round(clamp(100-d*.4,0,100));case'points':return Math.round(clamp(100-d*.02,0,100));case'average':return Math.round(clamp(100-d*20,0,100));default:return d===0?100:0;}}
function collectAnswers(){const a={};FIELDS.forEach(f=>{if(f.type==='height')a[f.id]=$('height').value.trim();else if(f.type==='text')a[f.id]=$(f.id).value.trim();else a[f.id]=$(f.id).value.trim();});return a;}
function scoreAnswers(player,answers){let total=0;const breakdown=FIELDS.map(f=>{const answer=f.get(player);let guess=answers[f.id];let score=0;if(f.type==='text')score=textScore(guess,f.aliases?f.aliases(player):[answer]);else{const n=f.type==='height'?parseHeight(guess):Number(guess);const alts=f.alts?f.alts(player):[];score=numericScore(f.type,n,answer,alts);}score=clamp(Math.round(score),0,100);total+=score;return{...f,guess,answer,score,correct:f.display(answer)};});return{score:total,breakdown};}
function clearForm(){FIELDS.forEach(f=>{$(f.id).value='';$(f.id).disabled=false;});updateFilled();}
function setFormDisabled(disabled){FIELDS.forEach(f=>$(f.id).disabled=disabled);$('submit-report').disabled=disabled;}
function updateFilled(){const a=collectAnswers();const n=Object.values(a).filter(v=>String(v).trim()!=='').length;$('live-filled').textContent=`${n} / ${FIELDS.length} filled`;}
function setMode(mode){if(state.running)return toast('Finish the active report first.','','error');state.mode=mode;qsa('[data-mode]').forEach(b=>b.classList.toggle('active',b.dataset.mode===mode));['daily','practice','race'].forEach(x=>$(x+'-panel').classList.toggle('hidden',x!==mode));const copy={daily:'One official report today. Same player for everyone.',practice:'Unlimited random scouting reports.',race:'Same player, same clock. Highest score wins.'};$('mode-description').textContent=copy[mode];$('results-shell').classList.add('hidden');$('scout-shell').classList.add('hidden');}
function startTimer(endAt){clearInterval(state.timer);state.endAt=endAt;function tick(){const ms=Math.max(0,state.endAt-Date.now());$('clock-value').textContent=(ms/1000).toFixed(1);$('clock-card').classList.toggle('urgent',ms<=10000&&ms>0);if(ms<=0){clearInterval(state.timer);if(state.running)finishReport(true);}}tick();state.timer=setInterval(tick,100);}
function showScout(player,kicker='SCOUT ASSIGNMENT',subtitle='Fill out everything you know. Close numeric guesses still score.'){
 state.player=player;state.answers=null;state.breakdown=null;state.score=0;state.timeMs=0;clearForm();$('player-name').textContent=player.name;$('assignment-kicker').textContent=kicker;$('assignment-subtitle').textContent=subtitle;$('results-shell').classList.add('hidden');$('scout-shell').classList.remove('hidden');$('race-opponent').classList.toggle('hidden',!['cpu','online'].includes(state.mode));window.scrollTo({top:$('scout-shell').offsetTop-90,behavior:'smooth'});
}
async function beginStandard(player,mode){state.mode=mode;showScout(player,mode==='daily'?'DAILY SCOUT':mode==='practice'?'PRACTICE SCOUT':'RACE ASSIGNMENT');state.running=true;state.startAt=Date.now();setFormDisabled(false);startTimer(state.startAt+RACE_MS);}
function formatTime(ms){return `${(ms/1000).toFixed(1)}s`;}
async function finishReport(auto=false){if(!state.running)return;state.running=false;clearInterval(state.timer);const now=Date.now();state.timeMs=clamp(now-state.startAt,0,RACE_MS);state.answers=collectAnswers();const result=scoreAnswers(state.player,state.answers);state.score=result.score;state.breakdown=result.breakdown;setFormDisabled(true);await persistResult();renderResults(auto);}
async function persistResult(){if(state.mode==='practice'){const key='stats_race_practice_best_v1';const prev=Number(localStorage.getItem(key)||0);if(state.score>prev)localStorage.setItem(key,String(state.score));updatePracticeBest();return;}
 if(state.mode==='daily'&&db&&state.user){try{const{error}=await db.rpc('stats_race_submit_daily',{p_challenge_date:todayCentral(),p_score:state.score,p_time_ms:Math.round(state.timeMs),p_answers:state.answers});if(error)throw error;}catch(e){toast('Daily score not saved',e.message,'error');}}
 if(state.mode==='online'&&db&&state.match){try{const{data,error}=await db.rpc('stats_race_submit_match',{p_match_id:state.match.id,p_score:state.score,p_time_ms:Math.round(state.timeMs)});if(error)throw error;if(data)state.match=data;}catch(e){toast('Race score not sent',e.message,'error');}}
}
function renderResults(auto=false){$('scout-shell').classList.add('hidden');$('results-shell').classList.remove('hidden');$('result-player').textContent=state.player.name;$('total-score').textContent=state.score.toLocaleString();const perfect=state.breakdown.filter(x=>x.score===100).length,partial=state.breakdown.filter(x=>x.score>0&&x.score<100).length,zero=FIELDS.length-perfect-partial;let raceText='';if(state.mode==='cpu'){raceText=state.score>state.cpuScore?'You won the race.':state.score<state.cpuScore?'CPU won the race.':'Dead even.';}else if(state.mode==='online'){raceText='Your report is filed. Waiting for the other scout if needed.';}
 $('result-copy').textContent=(auto?'Time expired. ':'')+(raceText||'Here is where your points came from.');$('result-summary').innerHTML=`<div class="summary-card"><span>Perfect fields</span><strong>${perfect}</strong><small>100 points each</small></div><div class="summary-card"><span>Partial fields</span><strong>${partial}</strong><small>Close guesses</small></div><div class="summary-card"><span>Zero fields</span><strong>${zero}</strong><small>No penalty</small></div><div class="summary-card"><span>Filed in</span><strong>${formatTime(state.timeMs)}</strong><small>Tie-break time</small></div>`+(state.mode==='cpu'?`<div class="summary-card"><span>CPU score</span><strong>${state.cpuScore}</strong><small>/ 1700</small></div>`:'');
 $('score-breakdown').innerHTML=state.breakdown.map(x=>`<div class="score-row ${x.score===100?'perfect':x.score>0?'partial':'zero'}"><span class="label">${escapeHtml(x.label)}</span><span class="guess">Your answer: ${escapeHtml(String(x.guess||'—'))}</span><span class="answer">Correct: ${escapeHtml(x.correct)}</span><span class="earned">+${x.score}</span></div>`).join('');
 $('result-next').textContent=state.mode==='daily'?'Practice another':state.mode==='online'?'Back to races':'Next report';$('result-leaderboard').classList.toggle('hidden',state.mode!=='daily');window.scrollTo({top:$('results-shell').offsetTop-90,behavior:'smooth'});if(state.mode==='online')watchMatchUntilComplete();}
function cpuRaceScore(player){let answers={};FIELDS.forEach(f=>{const a=f.get(player);if(f.type==='text'){answers[f.id]=Math.random()<.68?a:'';return;}let noise=0;switch(f.type){case'height':noise=Math.round((Math.random()-.5)*4);answers[f.id]=`${Math.floor((a+noise)/12)}'${(a+noise)%12}`;break;case'weight':answers[f.id]=Math.round(a+(Math.random()-.5)*34);break;case'jersey':answers[f.id]=Math.random()<.78?a:a+Math.ceil(Math.random()*5);break;case'year':answers[f.id]=Math.round(a+(Math.random()-.5)*5);break;case'pick':answers[f.id]=Math.max(1,Math.round(a+(Math.random()-.5)*10));break;case'award':answers[f.id]=Math.max(0,Math.round(a+(Math.random()-.5)*4));break;case'allstar':answers[f.id]=Math.max(0,Math.round(a+(Math.random()-.5)*7));break;case'games':answers[f.id]=Math.max(0,Math.round(a+(Math.random()-.5)*240));break;case'points':answers[f.id]=Math.max(0,Math.round(a+(Math.random()-.5)*5000));break;case'average':answers[f.id]=Math.max(0,Math.round((a+(Math.random()-.5)*5)*10)/10);break;}});return scoreAnswers(player,answers).score;}
async function startCpuRace(){const p=randomPlayer(state.lastPractice);state.lastPractice=p.id;state.mode='cpu';state.cpuScore=cpuRaceScore(p);$('opponent-name').textContent='CPU Scout';$('opponent-state').textContent='Scouting…';await beginStandard(p,'cpu');}
async function startPractice(){const p=randomPlayer(state.lastPractice);state.lastPractice=p.id;await beginStandard(p,'practice');}
async function startDaily(){const p=dailyPlayer();if(db&&state.user){try{const{data,error}=await db.rpc('stats_race_start_daily',{p_challenge_date:todayCentral(),p_player_id:p.id});if(error)throw error;state.dailyRow=data;if(data?.finished_at){toast('Daily already filed','Your official report is complete. Practice mode is still unlimited.','error');return;}const started=new Date(data.started_at).getTime();const end=started+RACE_MS;if(Date.now()>=end){toast('Daily clock expired','This official attempt has already expired.','error');await db.rpc('stats_race_submit_daily',{p_challenge_date:todayCentral(),p_score:0,p_time_ms:RACE_MS,p_answers:{}});updateDailyStatus();return;}state.mode='daily';showScout(p,'DAILY SCOUT','One official report. The clock is tied to the server start time.');state.running=true;state.startAt=started;setFormDisabled(false);startTimer(end);return;}catch(e){toast('Could not start Daily',e.message,'error');return;}}
 await beginStandard(p,'daily');toast('Guest Daily','Log in to record an official leaderboard score.');}
function updatePracticeBest(){const best=Number(localStorage.getItem('stats_race_practice_best_v1')||0);$('practice-best').textContent=best?`Best practice score: ${best.toLocaleString()} / ${MAX_SCORE}`:'Best practice score: —';}
async function updateDailyStatus(){const p=dailyPlayer();if(!db||!state.user){$('daily-status').textContent=`Today's player is locked until you start. Log in to save one official score.`;return;}try{const{data}=await db.from('stats_race_daily_scores').select('score,time_ms,finished_at,started_at').eq('user_id',state.user.id).eq('challenge_date',todayCentral()).maybeSingle();if(!data)$('daily-status').textContent='Official attempt available.';else if(data.finished_at)$('daily-status').textContent=`Official score: ${(data.score||0).toLocaleString()} / ${MAX_SCORE} · ${formatTime(data.time_ms||RACE_MS)}`;else $('daily-status').textContent='Official attempt started but not filed yet.';}catch{$('daily-status').textContent='Could not check Daily status.';}}
async function openDailyLeaderboard(){if(!db)return openModal('<span class="overline">DAILY LEADERBOARD</span><h2>Online setup required.</h2><p class="modal-note">Connect Supabase to save and compare official Daily scores.</p>');const date=todayCentral();const{data:scores,error}=await db.rpc('stats_race_daily_leaderboard',{p_challenge_date:date});if(error)return toast('Leaderboard failed',error.message,'error');openModal(`<span class="overline">DAILY SCOUT · ${date}</span><h2>Leaderboard</h2><p class="modal-note">Highest score wins. Filing time breaks ties. No speed bonus is added to the score.</p>${(scores||[]).length?(scores||[]).map(r=>`<div class="leader-row"><span class="rank">${r.rank}</span><span><strong>${escapeHtml(r.username||'HoopLoop player')}</strong><small>${formatTime(r.time_ms||RACE_MS)}</small></span><strong>${Number(r.score||0).toLocaleString()}</strong></div>`).join(''):'<p class="modal-note">No completed reports yet.</p>'}`);}
async function loadIdentity(){if(!db){$('online-status').textContent='Online races require Supabase.';return;}const{data:{session}}=await db.auth.getSession();state.user=session?.user||null;if(state.user){const{data:p}=await db.from('profiles').select('id,username').eq('id',state.user.id).maybeSingle();state.profile=p||null;$('account-label').textContent=p?.username||'Account';$('online-status').textContent=`Signed in as ${p?.username||'HoopLoop player'}.`;subscribeInvites();}else{$('online-status').textContent='Log in from Account to race friends or random players.';}$('race-friend').disabled=!state.user;$('race-random').disabled=!state.user;$('race-invites').disabled=!state.user;updateDailyStatus();}
async function acceptedFriends(){if(!db||!state.user)return[];const{data}=await db.from('friendships').select('requester_id,addressee_id,requester:profiles!friendships_requester_id_fkey(id,username),addressee:profiles!friendships_addressee_id_fkey(id,username)').eq('status','accepted').or(`requester_id.eq.${state.user.id},addressee_id.eq.${state.user.id}`);return(data||[]).map(r=>r.requester_id===state.user.id?r.addressee:r.requester).filter(Boolean);}
async function chooseFriendRace(){if(!state.user)return;const friends=await acceptedFriends();openModal(`<span class="overline">STATS RACE</span><h2>Choose a friend.</h2><p class="modal-note">They'll receive an invite for the same 90-second scouting report.</p>${friends.length?friends.map(f=>`<div class="friend-row"><span class="rank">VS</span><span><strong>${escapeHtml(f.username)}</strong><small>Friend</small></span><button class="primary-button" data-race-friend="${escapeHtml(f.username)}">Invite</button></div>`).join(''):'<p class="modal-note">No accepted friends yet. Add friends from the HoopLoop Friends tab.</p>'}`);qsa('[data-race-friend]').forEach(b=>b.onclick=()=>createFriendRace(b.dataset.raceFriend));}
async function createFriendRace(username){const p=randomPlayer();const{data,error}=await db.rpc('stats_race_create_friend_match',{p_friend_username:username,p_player_id:p.id});if(error)return toast('Invite failed',error.message,'error');closeModal();state.match=data;state.matchRole='host';toast('Invite sent',`Waiting for ${username}.`);watchMatch(data.id);}
async function findRandomRace(){const p=randomPlayer();$('online-status').textContent='Searching for a Stats Race opponent…';const{data,error}=await db.rpc('stats_race_find_random_match',{p_player_id:p.id});if(error)return toast('Matchmaking failed',error.message,'error');state.match=data;state.matchRole=data.host_id===state.user.id?'host':'guest';watchMatch(data.id);if(data.status==='searching')$('online-status').textContent='Searching… keep this page open.';}
async function openInvites(){if(!state.user)return;const{data,error}=await db.from('stats_race_matches').select('id,player_id,created_at,host_id,host:profiles!stats_race_matches_host_id_fkey(username)').eq('guest_id',state.user.id).eq('status','invited').order('created_at',{ascending:false});if(error)return toast('Invites failed',error.message,'error');openModal(`<span class="overline">STATS RACE</span><h2>Race invites</h2>${(data||[]).length?(data||[]).map(r=>`<div class="invite-row"><span class="rank">VS</span><span><strong>${escapeHtml(r.host?.username||'Friend')}</strong><small>90-second scouting race</small></span><button class="primary-button" data-accept-match="${r.id}">Accept</button></div>`).join(''):'<p class="modal-note">No pending Stats Race invites.</p>'}`);qsa('[data-accept-match]').forEach(b=>b.onclick=()=>acceptMatch(b.dataset.acceptMatch));}
async function acceptMatch(id){const{data,error}=await db.rpc('stats_race_accept_match',{p_match_id:id});if(error)return toast('Could not accept',error.message,'error');closeModal();state.match=data;state.matchRole='guest';watchMatch(id);}
function subscribeInvites(){if(!db||!state.user)return;db.channel('stats-race-invites-'+state.user.id).on('postgres_changes',{event:'*',schema:'public',table:'stats_race_matches',filter:`guest_id=eq.${state.user.id}`},()=>updateInviteCount()).subscribe();updateInviteCount();}
async function updateInviteCount(){if(!db||!state.user)return;const{count}=await db.from('stats_race_matches').select('id',{count:'exact',head:true}).eq('guest_id',state.user.id).eq('status','invited');$('invite-count').textContent=count||'';$('invite-count').classList.toggle('hidden',!count);}
function watchMatch(id){if(state.channel)db.removeChannel(state.channel);state.channel=db.channel('stats-race-match-'+id).on('postgres_changes',{event:'*',schema:'public',table:'stats_race_matches',filter:`id=eq.${id}`},payload=>{state.match=payload.new;handleMatchState();}).subscribe();refreshMatch(id);}
async function refreshMatch(id){const{data,error}=await db.from('stats_race_matches').select('*').eq('id',id).single();if(!error){state.match=data;state.matchRole=data.host_id===state.user.id?'host':'guest';handleMatchState();}}
async function handleMatchState(){const m=state.match;if(!m)return;if(m.status==='invited'){$('online-status').textContent='Friend invite sent. Waiting for acceptance…';return;}if(m.status==='searching'){$('online-status').textContent='Searching for a random opponent…';return;}if(['countdown','live'].includes(m.status)){const p=PLAYERS.find(x=>x.id===m.player_id)||PLAYERS[0];const start=new Date(m.starts_at).getTime(),end=new Date(m.ends_at).getTime();if(Date.now()<start){$('online-status').textContent='Opponent found. Race starts in a moment…';showScout(p,'HEAD-TO-HEAD RACE','Both scouts receive the same player and the same 90-second clock.');state.mode='online';state.running=false;setFormDisabled(true);$('race-opponent').classList.remove('hidden');$('opponent-name').textContent='Opponent';const countdown=setInterval(()=>{const left=Math.ceil((start-Date.now())/1000);$('clock-value').textContent=left>0?String(left):'GO';if(left<=0){clearInterval(countdown);beginOnlineLive(p,start,end);}},100);return;}if(!state.running&&!state.answers)beginOnlineLive(p,start,end);return;}if(m.status==='complete')renderOnlineFinal();}
function beginOnlineLive(p,start,end){state.mode='online';state.player=p;state.startAt=start;state.endAt=end;state.running=true;clearForm();setFormDisabled(false);$('player-name').textContent=p.name;$('assignment-kicker').textContent='HEAD-TO-HEAD RACE';$('assignment-subtitle').textContent='Same player. Same clock. Highest scouting score wins.';$('race-opponent').classList.remove('hidden');$('opponent-state').textContent='Scouting…';startTimer(end);}
async function watchMatchUntilComplete(){if(!state.match||!db)return;const myRole=state.matchRole;const oppScore=myRole==='host'?state.match.guest_score:state.match.host_score;if(oppScore!=null)return renderOnlineFinal();$('opponent-state').textContent='Waiting for opponent…';const end=new Date(state.match.ends_at).getTime();const finalize=async()=>{await db.rpc('stats_race_finalize_match',{p_match_id:state.match.id});refreshMatch(state.match.id);};if(Date.now()>=end)finalize();else setTimeout(finalize,Math.max(0,end-Date.now()+300));}
function renderOnlineFinal(){const m=state.match;if(!m||m.status!=='complete')return;const mine=state.matchRole==='host'?m.host_score:m.guest_score,theirs=state.matchRole==='host'?m.guest_score:m.host_score,myTime=state.matchRole==='host'?m.host_time_ms:m.guest_time_ms,theirTime=state.matchRole==='host'?m.guest_time_ms:m.host_time_ms;let result=mine>theirs?'You won.':mine<theirs?'Opponent won.':myTime<theirTime?'Tie score — you won on time.':myTime>theirTime?'Tie score — opponent won on time.':'Perfect tie.';$('opponent-state').textContent=`Final: ${Number(theirs||0).toLocaleString()}`;if(!$('results-shell').classList.contains('hidden'))$('result-copy').textContent=`${result} You ${Number(mine||0).toLocaleString()} — ${Number(theirs||0).toLocaleString()} Opponent.`;else toast('Race complete',`${result} ${mine||0}–${theirs||0}`);}
function scoringRules(){openModal(`<span class="overline">SCORING</span><h2>Perfect = 100.</h2><p class="modal-note">There are 17 fields and no negative points. Text facts are 100 for an accepted correct answer. Numeric fields gradually lose points as your guess moves away from the real answer.</p><div class="leader-row"><span class="rank">100</span><span><strong>Exact</strong><small>Perfect answer</small></span><strong>Full credit</strong></div><div class="leader-row"><span class="rank">≈</span><span><strong>Close</strong><small>Example: 1 inch off, or a nearby career average</small></span><strong>Partial</strong></div><div class="leader-row"><span class="rank">0</span><span><strong>Miss / blank</strong><small>No punishment</small></span><strong>No points</strong></div><p class="modal-note">Daily and online ties are broken by how quickly the report was filed, but speed never adds points.</p>`);}
function nextFromResults(){if(state.mode==='daily'||state.mode==='practice'||state.mode==='cpu'){setMode('practice');startPractice();}else{setMode('race');}}
function wire(){qsa('[data-mode]').forEach(b=>b.onclick=()=>setMode(b.dataset.mode));$('jump-play').onclick=()=>$('play-section').scrollIntoView({behavior:'smooth'});$('how-button').onclick=scoringRules;$('modal-close').onclick=closeModal;$('modal-backdrop').onclick=e=>{if(e.target===$('modal-backdrop'))closeModal();};FIELDS.forEach(f=>$(f.id).addEventListener('input',updateFilled));$('scout-form').onsubmit=e=>{e.preventDefault();finishReport(false);};$('start-daily').onclick=startDaily;$('start-practice').onclick=startPractice;$('start-cpu-race').onclick=startCpuRace;$('daily-leaderboard').onclick=openDailyLeaderboard;$('result-leaderboard').onclick=openDailyLeaderboard;$('result-next').onclick=nextFromResults;$('race-friend').onclick=chooseFriendRace;$('race-random').onclick=findRandomRace;$('race-invites').onclick=openInvites;}
async function init(){wire();updatePracticeBest();if(!PLAYERS.length){toast('Stats Race data missing','stats-race-data.js did not load.','error');return;}await loadIdentity();}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();
