(() => {
'use strict';
const DATA=window.HOOPLOOP_STATS_RACE_DATA||{players:[],meta:{}};
const PLAYERS=DATA.players||[], RACE_MS=90000;
const $=id=>document.getElementById(id), qsa=s=>[...document.querySelectorAll(s)];
const cfg=window.HOOPLOOP_CONFIG||{};
const configured=Boolean(window.supabase)&&/^https:\/\/.+\.supabase\.co$/i.test(String(cfg.SUPABASE_URL||''))&&Boolean(cfg.SUPABASE_ANON_KEY)&&!String(cfg.SUPABASE_ANON_KEY).includes('PASTE_');
const db=configured?window.supabase.createClient(cfg.SUPABASE_URL,cfg.SUPABASE_ANON_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}}):null;
const BASE_FIELDS=[
 {id:'height',label:'Height',type:'height',get:p=>p.heightInches,display:v=>`${Math.floor(v/12)}'${v%12}"`},
 {id:'weight',label:'Weight',type:'weight',get:p=>p.weight,display:v=>`${v} lb`},
 {id:'position',label:'Primary position',type:'text',get:p=>p.primaryPosition,aliases:p=>p.positionAliases,display:v=>v},
 {id:'college',label:'College / route',type:'text',get:p=>p.college,aliases:p=>p.collegeAliases,display:v=>v},
 {id:'country',label:'Country / basketball nationality',type:'text',get:p=>p.country,aliases:p=>p.countryAliases,display:v=>v},
 {id:'hometown',label:'Hometown / birthplace',type:'text',get:p=>p.hometown,aliases:p=>p.hometownAliases,display:v=>v},
 {id:'shootingHand',label:'Shooting hand',type:'exactText',get:p=>p.shootingHand,aliases:p=>p.shootingHandAliases,display:v=>v},
 {id:'jersey',label:'NBA jersey numbers',type:'multi-number',get:p=>p.jerseyNumbers,display:v=>v.map(n=>`#${n}`).join(', ')},
 {id:'teams',label:'NBA teams played for',type:'multi-teams',get:p=>p.teams||[],display:v=>v.join(', ')},
 {id:'draftYear',label:'Draft year',type:'year',get:p=>p.draftYear,display:v=>String(v)},
 {id:'draftPick',label:'Draft pick',type:'pick',get:p=>p.draftPick,display:v=>`#${v}`},
 {id:'championships',label:'Championships',type:'resumeCount',get:p=>p.championships,display:v=>String(v)},
 {id:'mvps',label:'Regular-season MVPs',type:'resumeCount',get:p=>p.mvps,display:v=>String(v)},
 {id:'finalsMvps',label:'Finals MVPs',type:'resumeCount',get:p=>p.finalsMvps,display:v=>String(v)},
 {id:'roty',label:'Rookie of the Year awards',type:'resumeCount',get:p=>p.roty,display:v=>String(v)},
 {id:'dpoy',label:'Defensive Player of the Year awards',type:'resumeCount',get:p=>p.dpoy,display:v=>String(v)},
 {id:'allStars',label:'All-Star selections',type:'resumeCount',get:p=>p.allStars,display:v=>String(v)},
 {id:'allNbaTeams',label:'All-NBA selections',type:'resumeCount',get:p=>p.allNbaTeams,display:v=>String(v)},
 {id:'ppg',label:'Career PPG',type:'average',get:p=>p.ppg,display:v=>Number(v).toFixed(1)},
 {id:'rpg',label:'Career RPG',type:'average',get:p=>p.rpg,display:v=>Number(v).toFixed(1)},
 {id:'apg',label:'Career APG',type:'average',get:p=>p.apg,display:v=>Number(v).toFixed(1)},
 {id:'spg',label:'Career SPG',type:'average',get:p=>p.spg,display:v=>Number(v).toFixed(1)},
 {id:'bpg',label:'Career BPG',type:'average',get:p=>p.bpg,display:v=>Number(v).toFixed(1)},
 {id:'tpg',label:'Career TPG',type:'average',get:p=>p.tpg,display:v=>Number(v).toFixed(1)},
 {id:'fgPct',label:'Career FG%',type:'percentage',get:p=>p.fgPct,display:v=>`${Number(v).toFixed(1)}%`},
 {id:'tripleDoubles',label:'Career triple-doubles',type:'statCount',get:p=>p.tripleDoubles,display:v=>Number(v).toLocaleString()}
];
const RETIRED_EXTRA=[
 {id:'games',label:'Games played',type:'games',get:p=>p.games,display:v=>Number(v).toLocaleString()},
 {id:'points',label:'Career points',type:'points',get:p=>p.points,display:v=>Number(v).toLocaleString()},
 {id:'seasonsPlayed',label:'NBA seasons played',type:'resumeCount',get:p=>p.seasonsPlayed,display:v=>String(v)}
];
const CURRENT_EXTRA=[
 {id:'careerHighPoints',label:'Career-high points',type:'careerHigh',get:p=>p.careerHighPoints,display:v=>String(v)},
 {id:'careerHighRebounds',label:'Career-high rebounds',type:'careerHigh',get:p=>p.careerHighRebounds,display:v=>String(v)},
 {id:'careerHighAssists',label:'Career-high assists',type:'careerHigh',get:p=>p.careerHighAssists,display:v=>String(v)},
 {id:'careerEarningsM',label:'NBA salary earned through 2025-26',type:'money',get:p=>p.careerEarningsM,display:v=>`~$${Number(v).toFixed(1)}M`}
];
const ALL_FIELD_IDS=['height','weight','position','college','country','hometown','shootingHand','jersey','teams','draftYear','draftPick','championships','mvps','finalsMvps','roty','dpoy','allStars','allNbaTeams','games','points','seasonsPlayed','careerHighPoints','careerHighRebounds','careerHighAssists','careerEarningsM','ppg','rpg','apg','spg','bpg','tpg','fgPct','tripleDoubles'];
const state={mode:'daily',pool:'retired',player:null,running:false,startAt:0,endAt:0,timer:null,answers:null,breakdown:null,score:0,maxScore:2900,timeMs:0,user:null,profile:null,dailyRow:null,cpuScore:null,match:null,channel:null,matchRole:null,lastPractice:null,practiceUntimed:false};
function fieldsFor(playerOrPool=state.player||state.pool){const pool=typeof playerOrPool==='string'?playerOrPool:playerOrPool.pool;const fs=[...BASE_FIELDS,...(pool==='current'?CURRENT_EXTRA:RETIRED_EXTRA)];if(typeof playerOrPool==='string')return fs;return fs.filter(f=>f.get(playerOrPool)!==undefined&&f.get(playerOrPool)!==null);}
function maxScoreFor(playerOrPool=state.player||state.pool){return fieldsFor(playerOrPool).length*100;}
function poolPlayers(pool=state.pool){return PLAYERS.filter(p=>p.pool===pool);}
function escapeHtml(s){return String(s??'').replace(/[&<>'\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','\"':'&quot;'}[c]));}
function norm(s){return String(s??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toUpperCase().replace(/[^A-Z0-9]+/g,' ').trim();}
function clamp(v,a,b){return Math.max(a,Math.min(b,v));}
function hash(str){let h=2166136261;for(let i=0;i<str.length;i++){h^=str.charCodeAt(i);h=Math.imul(h,16777619);}return h>>>0;}
function todayCentral(){const parts=new Intl.DateTimeFormat('en-US',{timeZone:'America/Chicago',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date());const o={};parts.forEach(p=>o[p.type]=p.value);return `${o.year}-${o.month}-${o.day}`;}
function dailyPlayer(date=todayCentral(),pool=state.pool){const arr=poolPlayers(pool);return arr[hash(`stats-race-v4:${pool}:${date}`)%arr.length];}
function randomPlayer(excludeId='',pool=state.pool){const arr=poolPlayers(pool).filter(p=>p.id!==excludeId);return arr[Math.floor(Math.random()*arr.length)]||poolPlayers(pool)[0];}
function toast(title,msg='',kind='success'){const n=document.createElement('div');n.className=`toast ${kind}`;n.innerHTML=`<strong>${escapeHtml(title)}</strong>${msg?`<div>${escapeHtml(msg)}</div>`:''}`;$('toast-region').appendChild(n);setTimeout(()=>n.remove(),4200);}
function openModal(html){$('modal-content').innerHTML=html;$('modal-backdrop').classList.remove('hidden');}
function closeModal(){$('modal-backdrop').classList.add('hidden');$('modal-content').innerHTML='';}
function parseHeight(v){const s=String(v||'').trim();if(!s)return NaN;const nums=s.match(/\d+(?:\.\d+)?/g)||[];if(s.includes("'")||nums.length>=2)return Number(nums[0])*12+Number(nums[1]||0);const n=Number(nums[0]);if(!Number.isFinite(n))return NaN;if(n>=48&&n<=100)return n;if(n>=5&&n<8)return Math.round(n*12);return NaN;}
function textScore(raw,aliases){const guess=norm(raw);if(!guess)return 0;const vals=[...new Set((aliases||[]).map(norm).filter(Boolean))];if(vals.includes(guess))return 100;for(const a of vals){if(guess.length>=4&&(a.includes(guess)||guess.includes(a)))return 70;}return 0;}
function exactTextScore(raw,aliases){const guess=norm(raw);if(!guess)return 0;return (aliases||[]).map(norm).includes(guess)?100:0;}
function resumeStep(d){return d===0?100:d===1?80:d===2?50:d===3?25:0;}
function numericScore(type,guess,answer){if(!Number.isFinite(guess))return 0;const d=Math.abs(guess-answer);switch(type){
 case'height':return d===0?100:d===1?75:d===2?45:0;
 case'weight':return d<=2?100:d<=5?80:d<=10?55:d<=20?25:0;
 case'year':return d===0?100:d===1?75:d===2?35:0;
 case'pick':return d===0?100:d<=2?80:d<=5?55:d<=10?30:0;
 case'resumeCount':return resumeStep(d);
 case'games':return Math.max(0,100-d*.5);
 case'points':return Math.max(0,100-d*.025);
 case'average':return Math.max(0,100-d*20);
 case'percentage':return Math.max(0,100-d*12.5);
 case'careerHigh':return Math.max(0,100-d*5);
 case'statCount':{const tol=Math.max(1,Math.abs(answer)*.05);const r=d/tol;return r===0?100:r<=1?90:r<=2?75:r<=4?50:r<=7?25:0;}
 case'money':{const pct=answer?d/Math.abs(answer):d;return pct<=.01?100:pct<=.05?90:pct<=.10?75:pct<=.20?50:pct<=.35?25:0;}
 default:return d===0?100:0;}}
function multiNumberScore(raw,correct){const guesses=[...new Set((String(raw||'').match(/\d+/g)||[]).map(Number))];if(!guesses.length)return 0;const c=new Set(correct.map(Number)),hit=guesses.filter(x=>c.has(x)).length,wrong=guesses.length-hit;if(!hit)return 0;const coverage=hit/c.size;return (80+20*coverage)*Math.max(.70,1-.06*wrong);}
function genericTeamAliases(team){const n=norm(team),parts=n.split(' ').filter(Boolean),out=[n];if(parts.length>1){out.push(parts.slice(0,-1).join(' '),parts.at(-1));if(parts.length>2)out.push(parts.slice(-2).join(' '));}return out;}
function teamAliasesFor(team,player){return [...new Set([team,...(player.teamAliases?.[team]||[]),...genericTeamAliases(team)].map(norm).filter(Boolean))];}
function multiTeamScore(raw,player){const chunks=String(raw||'').split(/[,;\/\n|]+/).map(norm).filter(Boolean);if(!chunks.length)return 0;const teams=player.teams||[];let hit=0,wrong=0;const hitTeams=new Set();for(const ch of chunks){let recognized=false;for(const t of teams){const vals=teamAliasesFor(t,player);if(vals.some(a=>a===ch||a.includes(ch)||ch.includes(a))){recognized=true;hitTeams.add(t);}}if(!recognized&&ch.length>2)wrong++;}hit=hitTeams.size;if(!hit)return 0;const coverage=hit/teams.length;return (80+20*coverage)*Math.max(.70,1-.06*wrong);}
function collectAnswers(){const a={};fieldsFor(state.player||state.pool).forEach(f=>{const el=$(f.id);a[f.id]=el?el.value.trim():'';});return a;}
function scoreAnswers(player,answers){let total=0;const fs=fieldsFor(player);const breakdown=fs.map(f=>{const answer=f.get(player),guess=answers[f.id],aliases=f.aliases?f.aliases(player):[answer];let score=0;if(f.type==='text')score=textScore(guess,aliases);else if(f.type==='exactText')score=exactTextScore(guess,aliases);else if(f.type==='multi-number')score=multiNumberScore(guess,answer);else if(f.type==='multi-teams')score=multiTeamScore(guess,player);else {let n=f.type==='height'?parseHeight(guess):Number(String(guess).replace(/[$,]/g,'').replace(/\s*(million|m)$/i,''));score=numericScore(f.type,n,answer);}score=clamp(Math.round(score),0,100);total+=score;return{...f,guess,answer,score,correct:f.display(answer)};});return{score:total,maxScore:fs.length*100,breakdown};}
function clearForm(){ALL_FIELD_IDS.forEach(id=>{const el=$(id);if(el){el.value='';el.disabled=false;}});updateFieldVisibility();updateFilled();}
function setFormDisabled(disabled){fieldsFor(state.player||state.pool).forEach(f=>{const el=$(f.id);if(el)el.disabled=disabled;});$('submit-report').disabled=disabled;}
function updateFieldVisibility(){qsa('.retired-only').forEach(x=>x.classList.toggle('hidden',state.pool!=='retired'));qsa('.current-only').forEach(x=>x.classList.toggle('hidden',state.pool!=='current'));}
function updateFilled(){const a=collectAnswers();const n=Object.values(a).filter(v=>String(v).trim()!=='').length;$('live-filled').textContent=`${n} / ${fieldsFor(state.player||state.pool).length} filled`;}
function setPool(pool){if(state.running)return toast('Finish the active report first.','','error');state.pool=pool;state.player=null;qsa('[data-pool]').forEach(b=>b.classList.toggle('active',b.dataset.pool===pool));$('pool-note').textContent=pool==='retired'?`${poolPlayers('retired').length} audited retired profiles · career totals included`:`${poolPlayers('current').length} audited current profiles · through 2025-26`;updateFieldVisibility();updateDailyStatus();$('results-shell').classList.add('hidden');$('scout-shell').classList.add('hidden');}
function setMode(mode){if(state.running)return toast('Finish the active report first.','','error');state.mode=mode;qsa('[data-mode]').forEach(b=>b.classList.toggle('active',b.dataset.mode===mode));['daily','practice','race'].forEach(x=>$(x+'-panel').classList.toggle('hidden',x!==mode));const copy={daily:'One official report per pool today. Same player for everyone in that pool.',practice:'Unlimited random reports — timed or completely untimed.',race:'Same player, same clock. Highest score wins.'};$('mode-description').textContent=copy[mode];$('results-shell').classList.add('hidden');$('scout-shell').classList.add('hidden');}
function setPracticeTiming(untimed){if(state.running)return;state.practiceUntimed=untimed;qsa('[data-practice-time]').forEach(b=>b.classList.toggle('active',(b.dataset.practiceTime==='untimed')===untimed));$('practice-timing-note').textContent=untimed?'No clock. Keep going until you file the report.':'Classic 90-second practice report.';}
function startTimer(endAt){clearInterval(state.timer);state.endAt=endAt;$('clock-card').classList.remove('untimed');$('clock-card').querySelector('small').textContent='seconds';function tick(){const ms=Math.max(0,state.endAt-Date.now());$('clock-value').textContent=(ms/1000).toFixed(1);$('clock-card').classList.toggle('urgent',ms<=10000&&ms>0);if(ms<=0){clearInterval(state.timer);if(state.running)finishReport(true);}}tick();state.timer=setInterval(tick,100);}
function startUntimedClock() {clearInterval(state.timer);state.endAt=0;$('clock-card').classList.remove('urgent');$('clock-card').classList.add('untimed');$('clock-value').textContent='∞';$('clock-card').querySelector('small').textContent='untimed';}
function showScout(player,kicker='SCOUT ASSIGNMENT',subtitle='Fill out everything you know. Complete multi-answer fields for 100.'){state.player=player;state.pool=player.pool;state.answers=null;state.breakdown=null;state.score=0;state.maxScore=maxScoreFor(player);state.timeMs=0;clearForm();$('player-name').textContent=player.name;$('assignment-kicker').textContent=kicker;$('assignment-subtitle').textContent=subtitle;$('results-shell').classList.add('hidden');$('scout-shell').classList.remove('hidden');$('race-opponent').classList.toggle('hidden',!['cpu','online'].includes(state.mode));window.scrollTo({top:$('scout-shell').offsetTop-90,behavior:'smooth'});}
async function beginStandard(player,mode){state.mode=mode;showScout(player,mode==='daily'?'DAILY SCOUT':mode==='practice'?'PRACTICE SCOUT':'RACE ASSIGNMENT');state.running=true;state.startAt=Date.now();setFormDisabled(false);if(mode==='practice'&&state.practiceUntimed)startUntimedClock();else startTimer(state.startAt+RACE_MS);}
function formatTime(ms){if(!Number.isFinite(ms))return 'Untimed';return `${(ms/1000).toFixed(1)}s`;}
async function finishReport(auto=false){if(!state.running)return;state.running=false;clearInterval(state.timer);const elapsed=Date.now()-state.startAt;state.timeMs=(state.mode==='practice'&&state.practiceUntimed)?Math.max(0,elapsed):clamp(elapsed,0,RACE_MS);state.answers=collectAnswers();const result=scoreAnswers(state.player,state.answers);state.score=result.score;state.maxScore=result.maxScore;state.breakdown=result.breakdown;setFormDisabled(true);await persistResult();renderResults(auto);}
async function persistResult(){if(state.mode==='practice'){const key=`stats_race_practice_best_v4_${state.pool}`;const pct=state.score/state.maxScore;const prev=Math.max(Number(localStorage.getItem(key)||0),Number(localStorage.getItem(`stats_race_practice_best_v3_${state.pool}`)||0),Number(localStorage.getItem(`stats_race_practice_best_v2_${state.pool}`)||0));if(pct>prev)localStorage.setItem(key,String(pct));updatePracticeBest();return;}if(state.mode==='daily'&&db&&state.user){try{const{error}=await db.rpc('stats_race_submit_daily_v3',{p_challenge_date:todayCentral(),p_pool:state.pool,p_score:state.score,p_max_score:state.maxScore,p_time_ms:Math.round(state.timeMs),p_answers:state.answers});if(error)throw error;}catch(e){toast('Daily score not saved',e.message,'error');}}if(state.mode==='online'&&db&&state.match){try{const{data,error}=await db.rpc('stats_race_submit_match_v3',{p_match_id:state.match.id,p_score:state.score,p_max_score:state.maxScore,p_time_ms:Math.round(state.timeMs)});if(error)throw error;if(data)state.match=data;}catch(e){toast('Race score not sent',e.message,'error');}}}
function renderResults(auto=false){$('scout-shell').classList.add('hidden');$('results-shell').classList.remove('hidden');$('result-player').textContent=state.player.name;$('total-score').textContent=state.score.toLocaleString();$('total-max').textContent=`/ ${state.maxScore.toLocaleString()}`;const perfect=state.breakdown.filter(x=>x.score===100).length,partial=state.breakdown.filter(x=>x.score>0&&x.score<100).length,zero=state.breakdown.length-perfect-partial;let raceText='';if(state.mode==='cpu'){raceText=state.score>state.cpuScore?'You won the race.':state.score<state.cpuScore?'CPU won the race.':'Dead even.';}else if(state.mode==='online'){raceText='Your report is filed. Waiting for the other scout if needed.';}const timeLabel=(state.mode==='practice'&&state.practiceUntimed)?'Untimed':formatTime(state.timeMs);$('result-copy').textContent=(auto?'Time expired. ':'')+(raceText||`Report filed: ${state.score.toLocaleString()} / ${state.maxScore.toLocaleString()}.`);$('result-summary').innerHTML=`<div class="summary-card"><span>Perfect fields</span><strong>${perfect}</strong><small>100 points each</small></div><div class="summary-card"><span>Partial fields</span><strong>${partial}</strong><small>Close / incomplete</small></div><div class="summary-card"><span>Zero fields</span><strong>${zero}</strong><small>No negative points</small></div><div class="summary-card"><span>${state.mode==='practice'&&state.practiceUntimed?'Timing':'Filed in'}</span><strong>${timeLabel}</strong><small>${state.mode==='practice'&&state.practiceUntimed?'Practice has no deadline':'Tie-break time'}</small></div>`+(state.mode==='cpu'?`<div class="summary-card"><span>CPU score</span><strong>${state.cpuScore}</strong><small>/ ${state.maxScore}</small></div>`:'');$('score-breakdown').innerHTML=state.breakdown.map(r=>`<div class="score-row ${r.score===100?'perfect':r.score>0?'partial':'zero'}"><span class="label">${escapeHtml(r.label)}</span><span class="guess">You: ${escapeHtml(r.guess||'—')}</span><span class="answer">Answer: ${escapeHtml(r.correct)}</span><span class="earned">+${r.score}</span></div>`).join('');$('result-next').textContent=state.mode==='daily'?'Practice another':state.mode==='online'?'Back to races':'Next report';$('result-leaderboard').classList.toggle('hidden',state.mode!=='daily');window.scrollTo({top:$('results-shell').offsetTop-90,behavior:'smooth'});if(state.mode==='online')watchMatchUntilComplete();}
function cpuRaceScore(player){const max=maxScoreFor(player),r=Math.random();return Math.round(max*clamp(.45+r*.43+(Math.random()-.5)*.12,.25,.93));}
async function startCpuRace(){const p=randomPlayer(state.lastPractice);state.lastPractice=p.id;state.mode='cpu';state.cpuScore=cpuRaceScore(p);$('opponent-name').textContent='CPU Scout';$('opponent-state').textContent='Scouting…';await beginStandard(p,'cpu');}
async function startPractice(){const p=randomPlayer(state.lastPractice);state.lastPractice=p.id;await beginStandard(p,'practice');}
async function startDaily(){const p=dailyPlayer();if(db&&state.user){try{const{data,error}=await db.rpc('stats_race_start_daily_v3',{p_challenge_date:todayCentral(),p_pool:state.pool,p_player_id:p.id,p_max_score:maxScoreFor(p)});if(error)throw error;state.dailyRow=data;if(data?.finished_at){toast('Daily already filed',`Your official ${state.pool} report is complete.`,'error');return;}const started=new Date(data.started_at).getTime(),end=started+RACE_MS;if(Date.now()>=end){await db.rpc('stats_race_submit_daily_v3',{p_challenge_date:todayCentral(),p_pool:state.pool,p_score:0,p_max_score:maxScoreFor(p),p_time_ms:RACE_MS,p_answers:{}});toast('Daily clock expired','This official attempt has already expired.','error');updateDailyStatus();return;}state.mode='daily';showScout(p,'DAILY SCOUT',`${state.pool==='retired'?'Retired':'Current'} pool · one official report.`);state.running=true;state.startAt=started;setFormDisabled(false);startTimer(end);return;}catch(e){toast('Could not start Daily',e.message,'error');return;}}await beginStandard(p,'daily');toast('Guest Daily','Log in to record an official leaderboard score.');}
function updatePracticeBest(){const pct=Math.max(Number(localStorage.getItem(`stats_race_practice_best_v4_${state.pool}`)||0),Number(localStorage.getItem(`stats_race_practice_best_v3_${state.pool}`)||0),Number(localStorage.getItem(`stats_race_practice_best_v2_${state.pool}`)||0));if($('practice-best'))$('practice-best').textContent=pct?`Best: ${Math.round(pct*1000)/10}%`:'No practice score yet.';}
async function updateDailyStatus(){updatePracticeBest();if(!$('daily-status'))return;if(!db||!state.user){$('daily-status').textContent=`Today's ${state.pool} player is locked until you start. Log in to save one official score.`;return;}try{const{data}=await db.from('stats_race_daily_scores').select('score,max_score,time_ms,finished_at,started_at').eq('user_id',state.user.id).eq('challenge_date',todayCentral()).eq('pool',state.pool).maybeSingle();if(!data)$('daily-status').textContent=`Official ${state.pool} attempt available.`;else if(data.finished_at)$('daily-status').textContent=`Official score: ${(data.score||0).toLocaleString()} / ${(data.max_score||maxScoreFor()).toLocaleString()} · ${formatTime(data.time_ms||RACE_MS)}`;else $('daily-status').textContent='Official attempt started but not filed yet.';}catch{$('daily-status').textContent='Could not check Daily status.';}}
async function openDailyLeaderboard(){if(!db)return openModal('<span class="overline">DAILY LEADERBOARD</span><h2>Online setup required.</h2>');const{data:scores,error}=await db.rpc('stats_race_daily_leaderboard_v3',{p_challenge_date:todayCentral(),p_pool:state.pool});if(error)return toast('Leaderboard failed',error.message,'error');openModal(`<span class="overline">${state.pool.toUpperCase()} DAILY · ${todayCentral()}</span><h2>Leaderboard</h2><p class="modal-note">Highest percentage score wins. Raw score shown below. Filing time breaks exact percentage ties.</p>${(scores||[]).length?scores.map(r=>`<div class="leader-row"><span class="rank">${r.rank}</span><span><strong>${escapeHtml(r.username||'HoopLoop player')}</strong><small>${formatTime(r.time_ms||RACE_MS)}</small></span><strong>${Number(r.score||0).toLocaleString()} / ${Number(r.max_score||0).toLocaleString()}</strong></div>`).join(''):'<p class="modal-note">No completed reports yet.</p>'}`);}
async function loadIdentity(){if(!db){$('online-status').textContent='Online races need the existing HoopLoop Supabase connection.';return;}const{data:{session}}=await db.auth.getSession();state.user=session?.user||null;if(state.user){const{data:p}=await db.from('profiles').select('id,username').eq('id',state.user.id).maybeSingle();state.profile=p||null;$('account-label').textContent=p?.username||'Account';$('online-status').textContent=`Signed in as ${p?.username||'HoopLoop player'}.`;subscribeInvites();}else $('online-status').textContent='Log in from Account to race friends or random players.';$('race-friend').disabled=!state.user;$('race-random').disabled=!state.user;$('race-invites').disabled=!state.user;updateDailyStatus();}
async function acceptedFriends(){if(!db||!state.user)return[];const{data}=await db.from('friendships').select('requester_id,addressee_id,requester:profiles!friendships_requester_id_fkey(id,username),addressee:profiles!friendships_addressee_id_fkey(id,username)').eq('status','accepted').or(`requester_id.eq.${state.user.id},addressee_id.eq.${state.user.id}`);return(data||[]).map(r=>r.requester_id===state.user.id?r.addressee:r.requester).filter(Boolean);}
async function chooseFriendRace(){if(!state.user)return;const friends=await acceptedFriends();openModal(`<span class="overline">STATS RACE · ${state.pool.toUpperCase()}</span><h2>Choose a friend.</h2>${friends.length?friends.map(f=>`<div class="friend-row"><span class="rank">VS</span><span><strong>${escapeHtml(f.username)}</strong></span><button class="primary-button" data-race-friend="${escapeHtml(f.username)}">Invite</button></div>`).join(''):'<p class="modal-note">No accepted friends yet.</p>'}`);qsa('[data-race-friend]').forEach(b=>b.onclick=()=>createFriendRace(b.dataset.raceFriend));}
async function createFriendRace(username){const p=randomPlayer();const{data,error}=await db.rpc('stats_race_create_friend_match_v3',{p_friend_username:username,p_pool:state.pool,p_player_id:p.id,p_max_score:maxScoreFor(p)});if(error)return toast('Invite failed',error.message,'error');closeModal();state.match=data;state.matchRole='host';toast('Invite sent',`Waiting for ${username}.`);watchMatch(data.id);}
async function findRandomRace(){const p=randomPlayer();$('online-status').textContent=`Searching ${state.pool} pool…`;const{data,error}=await db.rpc('stats_race_find_random_match_v3',{p_pool:state.pool,p_player_id:p.id,p_max_score:maxScoreFor(p)});if(error)return toast('Matchmaking failed',error.message,'error');state.match=data;state.matchRole=data.host_id===state.user.id?'host':'guest';watchMatch(data.id);}
async function openInvites(){if(!state.user)return;const{data,error}=await db.from('stats_race_matches').select('id,player_id,pool,created_at,host_id,host:profiles!stats_race_matches_host_id_fkey(username)').eq('guest_id',state.user.id).eq('status','invited').order('created_at',{ascending:false});if(error)return toast('Invites failed',error.message,'error');openModal(`<span class="overline">STATS RACE</span><h2>Race invites</h2>${(data||[]).length?data.map(r=>`<div class="invite-row"><span class="rank">VS</span><span><strong>${escapeHtml(r.host?.username||'Friend')}</strong><small>${escapeHtml(r.pool||'retired')} pool</small></span><button class="primary-button" data-accept-match="${r.id}">Accept</button></div>`).join(''):'<p class="modal-note">No pending Stats Race invites.</p>'}`);qsa('[data-accept-match]').forEach(b=>b.onclick=()=>acceptMatch(b.dataset.acceptMatch));}
async function acceptMatch(id){const{data,error}=await db.rpc('stats_race_accept_match',{p_match_id:id});if(error)return toast('Could not accept',error.message,'error');closeModal();state.match=data;state.matchRole='guest';state.pool=data.pool||'retired';setPool(state.pool);watchMatch(id);}
function subscribeInvites(){if(!db||!state.user)return;db.channel('stats-race-invites-'+state.user.id).on('postgres_changes',{event:'*',schema:'public',table:'stats_race_matches',filter:`guest_id=eq.${state.user.id}`},()=>updateInviteCount()).subscribe();updateInviteCount();}
async function updateInviteCount(){if(!db||!state.user)return;const{count}=await db.from('stats_race_matches').select('id',{count:'exact',head:true}).eq('guest_id',state.user.id).eq('status','invited');$('invite-count').textContent=count||'';$('invite-count').classList.toggle('hidden',!count);}
function watchMatch(id){if(state.channel)db.removeChannel(state.channel);state.channel=db.channel('stats-race-match-'+id).on('postgres_changes',{event:'*',schema:'public',table:'stats_race_matches',filter:`id=eq.${id}`},payload=>{state.match=payload.new;handleMatchState();}).subscribe();refreshMatch(id);}
async function refreshMatch(id){const{data,error}=await db.from('stats_race_matches').select('*').eq('id',id).single();if(!error){state.match=data;state.matchRole=data.host_id===state.user.id?'host':'guest';state.pool=data.pool||'retired';handleMatchState();}}
async function handleMatchState(){const m=state.match;if(!m)return;if(m.status==='invited'){$('online-status').textContent='Friend invite sent. Waiting for acceptance…';return;}if(m.status==='searching'){$('online-status').textContent='Searching for a random opponent…';return;}if(['countdown','live'].includes(m.status)){const p=PLAYERS.find(x=>x.id===m.player_id)||poolPlayers(m.pool||'retired')[0];state.pool=p.pool;const start=new Date(m.starts_at).getTime(),end=new Date(m.ends_at).getTime();if(Date.now()<start){showScout(p,'HEAD-TO-HEAD RACE','Same player. Same report. Same 90-second clock.');state.mode='online';state.running=false;setFormDisabled(true);$('race-opponent').classList.remove('hidden');$('opponent-name').textContent='Opponent';const countdown=setInterval(()=>{const left=Math.ceil((start-Date.now())/1000);$('clock-value').textContent=left>0?String(left):'GO';if(left<=0){clearInterval(countdown);beginOnlineLive(p,start,end);}},100);return;}if(!state.running&&!state.answers)beginOnlineLive(p,start,end);return;}if(m.status==='complete')renderOnlineFinal();}
function beginOnlineLive(p,start,end){state.mode='online';state.player=p;state.pool=p.pool;state.startAt=start;state.endAt=end;state.running=true;clearForm();setFormDisabled(false);$('player-name').textContent=p.name;$('assignment-kicker').textContent='HEAD-TO-HEAD RACE';$('assignment-subtitle').textContent='Same player. Same report. Same clock.';$('race-opponent').classList.remove('hidden');$('opponent-state').textContent='Scouting…';startTimer(end);}
async function watchMatchUntilComplete(){if(!state.match||!db)return;const opp=state.matchRole==='host'?state.match.guest_score:state.match.host_score;if(opp!=null)return renderOnlineFinal();$('opponent-state').textContent='Waiting for opponent…';const end=new Date(state.match.ends_at).getTime();const finalize=async()=>{await db.rpc('stats_race_finalize_match',{p_match_id:state.match.id});refreshMatch(state.match.id);};if(Date.now()>=end)finalize();else setTimeout(finalize,Math.max(0,end-Date.now()+300));}
function renderOnlineFinal(){const m=state.match;if(!m||m.status!=='complete')return;const mine=state.matchRole==='host'?m.host_score:m.guest_score,theirs=state.matchRole==='host'?m.guest_score:m.host_score,myMax=state.matchRole==='host'?m.host_max_score:m.guest_max_score,theirMax=state.matchRole==='host'?m.guest_max_score:m.host_max_score,myTime=state.matchRole==='host'?m.host_time_ms:m.guest_time_ms,theirTime=state.matchRole==='host'?m.guest_time_ms:m.host_time_ms,myPct=(mine||0)/(myMax||1),theirPct=(theirs||0)/(theirMax||1);let result=myPct>theirPct?'You won.':myPct<theirPct?'Opponent won.':myTime<theirTime?'Tie score — you won on time.':myTime>theirTime?'Tie score — opponent won on time.':'Perfect tie.';$('opponent-state').textContent=`Final: ${Number(theirs||0).toLocaleString()} / ${Number(theirMax||0).toLocaleString()}`;if(!$('results-shell').classList.contains('hidden'))$('result-copy').textContent=`${result} You ${mine||0}/${myMax||0} — ${theirs||0}/${theirMax||0} Opponent.`;else toast('Race complete',result);}
function scoringRules(){openModal(`<span class="overline">SCORING · V4</span><h2>Résumé misses hurt now.</h2><p class="modal-note">Awards and résumé counts use a hard step curve: exact = 100, one away = 80, two away = 50, three away = 25, four or more away = 0. Career statistics stay more forgiving. Handedness is exact. Salary is scored by percentage error, and triple-doubles are regular-season only. No category can go negative.</p><div class="leader-row"><span class="rank">100</span><span><strong>Exact résumé answer</strong><small>Example: 3 All-NBA when the answer is 3</small></span><strong>Full</strong></div><div class="leader-row"><span class="rank">80</span><span><strong>One away</strong><small>2 or 4 when the answer is 3</small></span><strong>Strong</strong></div><div class="leader-row"><span class="rank">50</span><span><strong>Two away</strong><small>1 or 5 when the answer is 3</small></span><strong>Half</strong></div><div class="leader-row"><span class="rank">25</span><span><strong>Three away</strong><small>Last partial-credit step</small></span><strong>Low</strong></div>`);}
function nextFromResults(){if(state.mode==='daily'||state.mode==='practice'||state.mode==='cpu'){setMode('practice');startPractice();}else setMode('race');}
function wire(){qsa('[data-mode]').forEach(b=>b.onclick=()=>setMode(b.dataset.mode));qsa('[data-pool]').forEach(b=>b.onclick=()=>setPool(b.dataset.pool));qsa('[data-practice-time]').forEach(b=>b.onclick=()=>setPracticeTiming(b.dataset.practiceTime==='untimed'));$('jump-play').onclick=()=>$('play-section').scrollIntoView({behavior:'smooth'});$('how-button').onclick=scoringRules;$('modal-close').onclick=closeModal;$('modal-backdrop').onclick=e=>{if(e.target===$('modal-backdrop'))closeModal();};ALL_FIELD_IDS.forEach(id=>{const el=$(id);if(el)el.addEventListener('input',updateFilled);});$('scout-form').onsubmit=e=>{e.preventDefault();finishReport(false);};$('start-daily').onclick=startDaily;$('start-practice').onclick=startPractice;$('start-cpu-race').onclick=startCpuRace;$('daily-leaderboard').onclick=openDailyLeaderboard;$('result-leaderboard').onclick=openDailyLeaderboard;$('result-next').onclick=nextFromResults;$('race-friend').onclick=chooseFriendRace;$('race-random').onclick=findRandomRace;$('race-invites').onclick=openInvites;}
async function init(){wire();updateFieldVisibility();updatePracticeBest();setPracticeTiming(false);if(!PLAYERS.length)return toast('Stats Race data missing','stats-race-data.js did not load.','error');await loadIdentity();}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();
